Update flakiness script
bocoup/aria-at-gh-actions-helper pull request #30
Opened 2024-08-28 17:24 UTC by outofambit

2024-09-26 18:26 UTC, outofambit commented
@jugglinmike if you would take a look at this, that would be great! @gnarf already took a look and added a lot of great improvements via #34.

2024-10-02 21:03 UTC, jugglinmike requested changes
Between the need to silence npm's output and the parameterized source code, I think this script now warrants a CLI. Could you make a follow-up task for that?

2024-10-10 18:37 UTC, gnarf commented on stressor/stress-test.mts
> +  clearInterval(logStatusInterval);
sounds good

2024-10-10 18:41 UTC, gnarf commented on stressor/stress-test.mts
> +        JSON.stringify(baselineResponses);
I think it's just an Array<string>, JSON should be good for that, but I think that a better compare function is better on "memory" anyway - [`_.isEqual`](https://lodash.com/docs#isEqual) would probably nicely do the job, are you against importing that dependency, or should I embed a custom rewritten version of it?

2024-10-10 18:47 UTC, gnarf commented
> Between the need to silence npm's output and the parameterized source code, I think this script now warrants a CLI. Could you make a follow-up task for that?

I agree - It would be nice to be able to pass the parameters / specify filenames and could use a CLI front-end script.  @outofambit and I discussed how we were getting closer and closer to needing it. cc @ccanash "Add CLI front-end to stress test script" for a future task

2024-10-10 19:16 UTC, gnarf commented on stressor/stress-test.mts
> +  clearInterval(logStatusInterval);
f980db3

2024-10-10 19:17 UTC, gnarf commented on stressor/stress-test.mts
> +        JSON.stringify(baselineResponses);
f980db3 with isEqual - can always write an explicit loop `isStringArrayEqual` if needed

2024-10-10 19:17 UTC, gnarf commented on stressor/stress-test.mts
> +  clearInterval(logStatusInterval);
60e6181

2024-10-16 02:04 UTC, jugglinmike approved these changes
> I think it's just an Array, JSON should be good for that, but I think that a better compare function is better on "memory" anyway - [`_.isEqual`](https://lodash.com/docs#isEqual) would probably nicely do the job, are you against importing that dependency, or should I embed a custom rewritten version of it?

Thanks for calling that out. I agree that JSON serialization is a safe identity for arrays of strings; I must have misinterpreted the types. I'm still glad you followed through, anyway :)

2024-10-16 02:05 UTC, merged